server:
  port: 666

logging:
  level:
    org.springframework.web: ERROR
    org.hibernate: ERROR
  file:
    path: logs/

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cr7_mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    # 初始化数量
    initialSize: 1
    # 最大活跃数
    maxActive: 20
    # 最大连接等待超时时间
    maxWait: 60000
    # 打开PSCache，并且指定每个连接PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 通过connectionProperties属性来打开mergeSql功能；慢SQL记录
    # connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 配置监控统计拦截的filters，去掉后监控界面sql将无法统计,'wall'用于防火墙
    filters: stat, wall, log4j
    logSlowSql: true
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.qq.com #发送邮件服务器
    username: 2281572856@qq.com #QQ邮箱
    password: hivytrgskuvrecii  #客户端授权码
    protocol: smtp #发送邮件协议
    properties.mail.smtp.auth: true
    properties.mail.smtp.port: 465 #端口号465或587
    properties.mail.display.sendmail: AWMALL商城官方 #可以任意
    properties.mail.display.sendname: 好货推荐 #可以任意
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8
    from: 2281572856@qq.com #与上面的username保持一致t
  http:
    multipart:
      enabled: true
      max-file-size: 10Mb
      max-request-size: 100Mb